FROM node:20-alpine

RUN npm install -g @ionic/cli

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

EXPOSE 3048

CMD ["ionic", "serve", "--port", "3048", "--host", "0.0.0.0", "--no-open"]
